### ISSUE TITLE
m6anet inference pooling replicates 

### ISSUE THREAD

**Issue by sunsetyerin** [GoekeLab/m6anet#102]
**How many replicates m6anet can handle?** 
I tried 3 and 4 samples and it shows the following error message.
But when I tried 2 samples, it worked perfectly fine. 

`Traceback (most recent call last):
  File "/miniconda3/envs/m6anet/bin/m6anet", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/m6anet/__init__.py", line 30, in main
    args.func(args)
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/m6anet/scripts/inference.py", line 88, in main
    ds = NanopolishReplicateDS(input_dir, DEFAULT_MIN_READS, args.norm_path, mode='Inference')
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/m6anet/utils/data_utils.py", line 337, in __init__
    super().__init__(root_dir, min_reads, norm_path,
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/m6anet/utils/data_utils.py", line 77, in __init__
    self.initialize_data_info()
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/m6anet/utils/data_utils.py", line 357, in initialize_data_info
    read_info = pd.concat(all_read_info, axis=1)
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 258, in concat
    return op.get_result()
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 468, in get_result
    indexers[ax] = obj_labels.reindex(new_labels)[1]
  File "/miniconda3/envs/m6anet/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 2500, in reindex
    raise ValueError("cannot handle a non-unique multi-index!")
ValueError: cannot handle a non-unique multi-index!`

**Comment by chrishendra93** [comment]
hi @sunsetyerin, thanks for reporting this. m6Anet, by right, should assign unique sample names to each one of those replicates but this does not seem to be the case from the error message. Can you tell me what are the directories' name in this case and the specific command that you ran? Also can you try renaming the folders of each replicate and try again?

**Comment by sunsetyerin** [comment]
thanks it worked out
