### ISSUE TITLE
error with  m6anet dataprep

### ISSUE THREAD

**Issue by mocherry** [GoekeLab/m6anet#156]
Dear all,

after having struggled with m6Anet on Galaxy, where is has been running for days now, I resorted to give it a try on a windows system.

Now when running:
**m6anet dataprep --eventalign d:\temp\test.txt --out_dir d:\temp\output --n_processes 4**

I get the following long error, the indexing... occuring multiple times but at the end this occurs:

**_PerformanceWarning: indexing past lexsort depth may impact performance.
  pos_end += eventalign_result.loc[_index]['line_length'].sum()
Traceback (most recent call last):
  File "pandas\_libs\lib.pyx", line 2280, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "97.6604,109.208,107.283,102.632,104.076,104.717,108.406,106.161,104.076,103.755"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\Scripts\m6anet-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\__init__.py", line 30, in main
    args.func(args)
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\scripts\dataprep.py", line 68, in main
    parallel_preprocess_tx(args.eventalign, args.out_dir, args.n_processes,
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\dataprep_utils.py", line 383, in parallel_preprocess_tx
    data = combine(events_str)
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\dataprep_utils.py", line 291, in combine
    eventalign_result.loc[:, 'length'] = pd.to_numeric(eventalign_result['end_idx']) - \
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\pandas\core\tools\numeric.py", line 217, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]  # noqa
  File "pandas\_libs\lib.pyx", line 2322, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "97.6604,109.208,107.283,102.632,104.076,104.717,108.406,106.161,104.076,103.755" at position 0_**

Can anyone suggest a solution?

Thanks and best,
Matthias

**Comment by yuukiiwa** [comment]
Hi Matthias (@mocherry),

I think it is specific to pandas' problem in windows.

Thanks!

Best wishes,
Yuk Kei

**Comment by wangguiqian** [comment]
> Hi Matthias ([@mocherry](https://github.com/mocherry)),
> 
> I think it is specific to pandas' problem in windows.
> 
> Thanks!
> 
> Best wishes, Yuk Kei

(work) [gqwang@gpu02 Direct_RNA]$  singularity exec -B /public/home/gqwang/Workplate_data/Direct_RNA ~/Software/m6Anet_v2.1.sif m6anet dataprep --eventalign sx-90h_awk_fixed.txt --out_dir sx-90h_m6anet_data --n_processes 8
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 1897, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "80.0953,82.3358,84.2962,84.8564,82.3358,82.0557,88.2171,83.176,81.4956"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/m6anet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/m6anet/__init__.py", line 30, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/m6anet/scripts/dataprep.py", line 68, in main
    parallel_preprocess_tx(args.eventalign, args.out_dir, args.n_processes,
  File "/usr/local/lib/python3.8/site-packages/m6anet/utils/dataprep_utils.py", line 383, in parallel_preprocess_tx
    data = combine(events_str)
  File "/usr/local/lib/python3.8/site-packages/m6anet/utils/dataprep_utils.py", line 291, in combine
    eventalign_result.loc[:, 'length'] = pd.to_numeric(eventalign_result['end_idx']) - \
  File "/usr/local/lib/python3.8/site-packages/pandas/core/tools/numeric.py", line 150, in to_numeric
    values = lib.maybe_convert_numeric(
  File "pandas/_libs/lib.pyx", line 1934, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "80.0953,82.3358,84.2962,84.8564,82.3358,82.0557,88.2171,83.176,81.4956" at position 0


I also encountered this error. What could be the problem? When I run the command:
nanopolish eventalign 
--reads sx-50h.fq.gz 
--bam sx-50h_sorted.bam 
--genome ASFV_HLJ.fa 
--scale-events 
--signal-index 
--summary /dev/null 
--samples 
--threads 16 > sx-50h_eventalign_integer.txt
and then run
m6anet dataprep --eventalign, the above error occurs. I don't know what the situation is. Could it be because of the extra 'samples' column?
