### ISSUE TITLE
yet another error with m6anet dataprep

### ISSUE THREAD

**Issue by mocherry** [GoekeLab/m6anet#157]
Dear all,
now I get another error when running m6anet dataprep:

File "pandas\_libs\lib.pyx", line 2280, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "NNNNN"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\Scripts\m6anet-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\__init__.py", line 30, in main
    args.func(args)
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\scripts\dataprep.py", line 68, in main
    parallel_preprocess_tx(args.eventalign, args.out_dir, args.n_processes,
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\dataprep_utils.py", line 383, in parallel_preprocess_tx
    data = combine(events_str)
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\dataprep_utils.py", line 297, in combine
    eventalign_result.loc[:, 'sum_dwell_time'] = pd.to_numeric(eventalign_result['event_length']) \
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\pandas\core\tools\numeric.py", line 217, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]  # noqa
  File "pandas\_libs\lib.pyx", line 2322, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "NNNNN" at position 0

As always, help would be appreciated. Best,
Matthias

**Comment by yuukiiwa** [comment]
Hi Matthias (@mocherry),

I think it is specific to pandas' problem in windows.

Thanks!

Best wishes,
Yuk Kei
