### ISSUE TITLE
running with test eventalign test file file form github produces another error

### ISSUE THREAD

**Issue by mocherry** [GoekeLab/m6anet#158]
Dear all,

wouldn't have expected this causing so much trouble.
Now I have used the test-file from m6anet/tests/data and the ran:
m6anet inference --input_dir d:\temp\output --out_dir d:\temp\output  --n_processes 4 --num_iterations 1000

and got the following error:
Traceback (most recent call last):
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\Scripts\m6anet-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\__init__.py", line 30, in main
    args.func(args)
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\scripts\inference.py", line 100, in main
    ds = NanopolishDS(input_dir[0], DEFAULT_MIN_READS, args.norm_path, mode='Inference')
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\data_utils.py", line 100, in __init__
    self.set_feature_indices()
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\data_utils.py", line 109, in set_feature_indices
    self.total_neighboring_features = self.get_total_neighboring_features()
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\data_utils.py", line 149, in get_total_neighboring_features
    kmer, _ = self._load_data(self.data_fpath, tx_id, tx_pos, start_pos, end_pos)
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\site-packages\m6anet\utils\data_utils.py", line 185, in _load_data
    pos_info = json.loads(json_str)[tx_id][str(tx_pos)]
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\kirsch\AppData\Local\miniconda3\envs\m6anet\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 49895)

What am I doing wrong???

Best,
Matthias

**Comment by Fredxxx** [comment]
Dear Developer,

it seems that I have run into the same issue using your provided test data. 

With my limited understanding I think the json_str is not cropped correcltly. When modifying line 184 in data_utils.py to 
            json_str = f.read(end_pos - start_pos - 1) 
it seems to solve the JSON loading issue and the error message above disapears.

However, then another issue pops up in (so maybe the upper fix is not really a fix):
line 33, in run_inference
    for it, data in enumerate(dl): 
TypeError: __init__() missing 1 required positional argument: 'dtypes'

Could you please help with this issue? 

Best wishes
Fred

(I am using your code in pyCharm and could only make it run in Python 3.7)

**Comment by yuukiiwa** [comment]
Hi Fred (tagging you here @Fredxxx),

I am replying here instead of the email you sent me.

I think the issue with the json is that the `.tell()` in your python version and the python we use are different, which led to the -1 shift in the indexing. 

For the second error, can you try installing m6anet with python 3.8, instead? Are you using a window's system? If you are, can you try running m6anet on a linux system instead?

Thanks!

Best wishes,
Yuk Kei

**Comment by Fredxxx** [comment]
Hey Yuk Kei,

thank you for your response.

I could not get Python 3.8. running with torch 1.6., thus I tried it in Linux. If I run following script in Linux:

```
import os
import torch
import toml
import pkg_resources
import pathlib
import numpy as np
import warnings
from argparse import ArgumentParser
from argparse import ArgumentDefaultsHelpFormatter
from m6anet.model.model import MILModel
from m6anet.utils.constants import DEFAULT_MODEL_CONFIG,\
    DEFAULT_MIN_READS, DEFAULT_READ_THRESHOLD,\
    DEFAULT_NORM_PATH, PRETRAINED_CONFIGS,\
    DEFAULT_PRETRAINED_MODEL, DEFAULT_PRETRAINED_MODELS
from m6anet.utils.data_utils import NanopolishDS, NanopolishReplicateDS, inference_collate
from m6anet.utils.inference_utils import run_inference
from torch.utils.data import DataLoader

from m6anet.scripts import inference

if __name__ == '__main__':
    args = ArgumentParser(
            formatter_class=ArgumentDefaultsHelpFormatter,
            add_help=False
        )
    input_dir = ["/root/m6anet/tests/data"]
    args.out_dir = "/root/tt"
    args.model_config = DEFAULT_MODEL_CONFIG
    args.model_state_dict = None
    args.pretrained_model = DEFAULT_PRETRAINED_MODEL
    args.seed = 0
    args.device = 'cpu'
    args.n_processes = 4
    args.batch_size = 16

    if args.model_state_dict is not None:
        warnings.warn("--model_state_dict is specified, overwriting default model weights")
    else:
        if args.pretrained_model not in DEFAULT_PRETRAINED_MODELS:
            raise ValueError("Invalid pretrained model {}, must be one of {}".format(args.pretrained_model, DEFAULT_PRETRAINED_MODELS))

        args.model_state_dict = PRETRAINED_CONFIGS[args.pretrained_model][0]
        args.read_proba_threshold = PRETRAINED_CONFIGS[args.pretrained_model][1]
        args.norm_path = PRETRAINED_CONFIGS[args.pretrained_model][2]

    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)
    np.random.seed(args.seed)

    model = MILModel(toml.load(args.model_config)).to(args.device)
    model.load_state_dict(torch.load(args.model_state_dict,
                                     map_location=torch.device(args.device)))

    pathlib.Path(args.out_dir).mkdir(parents=True, exist_ok=True)

    with open(os.path.join(args.out_dir, "data.site_proba.csv"),'w', encoding='utf-8') as f:
        f.write('transcript_id,transcript_position,n_reads,probability_modified,kmer,mod_ratio\n')
    with open(os.path.join(args.out_dir, "data.indiv_proba.csv"), 'w', encoding='utf-8') as g:
        g.write('transcript_id,transcript_position,read_index,probability_modified\n')

    if len(input_dir) == 1:
        ds = NanopolishDS(input_dir[0], DEFAULT_MIN_READS, args.norm_path, mode='Inference')
    else:
        ds = NanopolishReplicateDS(input_dir, DEFAULT_MIN_READS, args.norm_path, mode='Inference')

    dl = DataLoader(ds, num_workers=args.n_processes, collate_fn=inference_collate, batch_size=args.batch_size,
                    shuffle=False)
    run_inference(model, dl, args)
```

Following error pops up:
`Traceback (most recent call last):
  File "/root/m6anetFred.py", line 111, in <module>
    run_inference(model, dl, args)
  File "/root/m6anet/utils/inference_utils.py", line 33, in run_inference
    for it, data in enumerate(dl):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 721, in reraise
    raise RuntimeError(msg) from None
RuntimeError: Caught JSONDecodeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/m6anet/utils/data_utils.py", line 213, in __getitem__
    tx_id, tx_pos, read_ids, features, kmer = self.load_data(idx)
  File "/root/m6anet/utils/data_utils.py", line 164, in load_data
    kmer, features = self._load_data(self.data_fpath, tx_id, tx_pos, start_pos, end_pos)
  File "/root/m6anet/utils/data_utils.py", line 185, in _load_data
    pos_info = json.loads(json_str)[tx_id][str(tx_pos)]
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Do you have any idea why that is?

Best wishes
Fred

**Comment by yuukiiwa** [comment]
Hi Fred,

You can change to `torch 1.8` to have `m6anet` installed with `python3.8`.

The `JSONDecodeError` means that your `json` file is corrupted that it cannot be recognized as a `json` format.

Thanks!

Best wishes,
Yuk Kei

**Comment by Fredxxx** [comment]
Hey Yuk Kei,

I can get it running with python 3.8 and torch 1.8. Thank you.

the JSON file is produced with your function:
`m6anet dataprep --eventalign /path/to/m6anet/m6anet/tests/data/eventalign.txt --out_dir /path/to/output --n_processes 4`

then running:
`m6anet inference --input_dir path/to/output --out_dir path/to/output  --n_processes 4 --num_iterations 1000`

gives the first error mentioned in this issue:
`Traceback (most recent call last):
  File "d:\users\fred\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\fred\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\Fred\AppData\Local\Programs\Python\Python37\Scripts\m6anet.exe\__main__.py", line 7, in <module>
  File "d:\users\fred\appdata\local\programs\python\python37\lib\site-packages\m6anet\__init__.py", line 30, in main
    args.func(args)
  File "d:\users\fred\appdata\local\programs\python\python37\lib\site-packages\m6anet\scripts\inference.py", line 100, in main
    ds = NanopolishDS(input_dir[0], DEFAULT_MIN_READS, args.norm_path, mode='Inference')
  File "d:\users\fred\appdata\local\programs\python\python37\lib\site-packages\m6anet\utils\data_utils.py", line 100, in __init__
    self.set_feature_indices()
  File "d:\users\fred\appdata\local\programs\python\python37\lib\site-packages\m6anet\utils\data_utils.py", line 109, in set_feature_indices
    self.total_neighboring_features = self.get_total_neighboring_features()
  File "d:\users\fred\appdata\local\programs\python\python37\lib\site-packages\m6anet\utils\data_utils.py", line 149, in get_total_neighboring_features
    kmer, _ = self._load_data(self.data_fpath, tx_id, tx_pos, start_pos, end_pos)
  File "d:\users\fred\appdata\local\programs\python\python37\lib\site-packages\m6anet\utils\data_utils.py", line 185, in _load_data
    pos_info = json.loads(json_str)[tx_id][str(tx_pos)]
  File "d:\users\fred\appdata\local\programs\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "d:\users\fred\appdata\local\programs\python\python37\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 20257)`

if I modify the code I still get the error below:

`D:\Fred\Software\m6anet\m6anetFred.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "D:\Fred\Software\m6anet\m6anetFred.py", line 68, in <module>
    run_inference(model, dl, args)
  File "D:\Fred\Software\m6anet\m6anet\utils\inference_utils.py", line 33, in run_inference
    for it, data in enumerate(dl):
  File "D:\Fred\Software\m6anet\venv\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\Fred\Software\m6anet\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "D:\Fred\Software\m6anet\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "D:\Fred\Software\m6anet\venv\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtypes'`

I am out of ideas, if you have one I would be very happy.

Best wishes
Frederik

**Comment by yuukiiwa** [comment]
Hi Frederik (@Fredxxx),

Can you upload the first 100 lines of the `eventalign.txt` file here so that I can see whether I can reproduce your errors with `m6anet dataprep`.

Thanks!

Best wishes,
Yuk Kei

**Comment by Fredxxx** [comment]
[eventalign_100.txt](https://github.com/GoekeLab/m6anet/files/14740699/eventalign_100.txt)

Thank zou

**Comment by yuukiiwa** [comment]
Hi Frederik (@Fredxxx),

Sorry that I can't reproduce your error. Test directory here --> [fred.tar.gz](https://github.com/GoekeLab/m6anet/files/14753607/fred.tar.gz)

I used a new environment and installed m6anet fresh with the following commands:
```
mamba create -n fred python=3.9
mamba activate fred
pip install numpy==1.26.4
pip install scikit-learn
pip install joblib
git clone https://github.com/GoekeLab/m6anet.git
cd m6anet
python setup.py install
cd ../
```

Then, I enlarged the `eventalign_100.txt` you provided by 25 times with the following code so that m6anet could run:
```
o=open('eventalign_100_25x.txt','w')
i=open('eventalign_100.txt','r')
o.write(i.readline())
k=[l.strip() for l in i]
for _ in range(25):
    for l in k:
        l=l.split('\t')
        o.write('\t'.join(l[:3]+[str(_)]+l[4:])+'\n')
i.close()
o.close()
```

Then I ran m6anet dataprep and inference with the enlarged `eventalign_100.txt` (now `eventalign_100_25x.txt'`)
```
m6anet dataprep --eventalign eventalign_100_25x.txt --out_dir dataprep
ls -lh dataprep/
total 36K
-rw-rw-r-- 1 wanyk wanyk  303 Mar 26 14:21 data.info
-rw-rw-r-- 1 wanyk wanyk  22K Mar 26 14:21 data.json
-rw-rw-r-- 1 wanyk wanyk  184 Mar 26 14:21 data.log
-rw-rw-r-- 1 wanyk wanyk 3.4K Mar 26 14:21 eventalign.index
```
```
m6anet inference --input_dir dataprep/ --out_dir inference
ls -lh inference/
total 12K
-rw-rw-r-- 1 wanyk wanyk 8.0K Mar 26 14:21 data.indiv_proba.csv
-rw-rw-r-- 1 wanyk wanyk  563 Mar 26 14:21 data.site_proba.csv
```

I couldn't reproduce your error, so it is likely that an issue specific to your computer.

Thanks!

Best wishes,
Yuk Kei
