### ISSUE TITLE
received 0 items of ancdata

### ISSUE THREAD

**Issue by dywang0323** [GoekeLab/m6anet#75]
I have some direct RNA data, when I run the following command, 
m6anet-run_inference --input_dir /ourdisk/hpc/rnafold/dywang/dont_archive/On_process/mocka59/m6A_v27 --out_dir /ourdisk/hpc/rnafold/dywang/dont_archive/On_process/mocka59/m6A_v27 --infer_mod_rate --n_processes 4

I got the error report 
Traceback (most recent call last):
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/oscer/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/oscer/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/opt/oscer/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/opt/oscer/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 803, in _try_get_data
    fs = [tempfile.NamedTemporaryFile() for i in range(fds_limit_margin)]
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 803, in <listcomp>
    fs = [tempfile.NamedTemporaryFile() for i in range(fds_limit_margin)]
  File "/opt/oscer/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/tempfile.py", line 541, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/opt/oscer/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 24] Too many open files: '/tmp/tmpkjiqmh_s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dywang/.local/bin/m6anet-run_inference", line 11, in <module>
    load_entry_point('m6anet==1.1.1', 'console_scripts', 'm6anet-run_inference')()
  File "/home/dywang/.local/lib/python3.8/site-packages/m6anet-1.1.1-py3.8.egg/m6anet/scripts/run_inference.py", line 72, in main
  File "/home/dywang/.local/lib/python3.8/site-packages/m6anet-1.1.1-py3.8.egg/m6anet/scripts/run_inference.py", line 67, in run_inference
  File "/home/dywang/.local/lib/python3.8/site-packages/m6anet-1.1.1-py3.8.egg/m6anet/utils/training_utils.py", line 225, in infer_mod_ratio
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/home/dywang/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 806, in _try_get_data
    raise RuntimeError(
RuntimeError: Too many open files. Communication with the workers is no longer possible. Please increase the limit using `ulimit -n` in the shell or change the sharing strategy by calling `torch.multiprocessing.set_sharing_strategy('file_system')` at the beginning of your code

**Comment by chrishendra93** [comment]
hi @dywang0323, try using --n_processes 0 to fix this. Alternatively, you can refer to this issue https://github.com/GoekeLab/m6anet/issues/38 where calling torch.multiprocessing.set_sharing_strategy('file_system') at the beginning of the run_inference.py seems to solve the issue

**Comment by dywang0323** [comment]
> hi @dywang0323, try using --n_processes 0 to fix this. Alternatively, you can refer to this issue #38 where calling torch.multiprocessing.set_sharing_strategy('file_system') at the beginning of the run_inference.py seems to solve the issue

Thanks a lot for the help! using --n_processes 0 works for the issue
